apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: myapp
        image: asia-northeast1-docker.pkg.dev/civil-campaign-244100/chanhu-profile-site/web-app:stable
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name:  web-app-service
spec:
  selector:
    app: web-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
