apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-admin
secrets:
  - name: git-cred
  - name: docker-cred
imagePullSecrets:
  - name: artifact-registry

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-admin-role
rules:
  - apiGroups: ["*"]
    resources: ["pod", "deployments", "services"]
    verbs: ["*"] #full-control

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-admin-role
subjects:
  - kind: ServiceAccount
    name: tekton-admin
