apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git2img-pipeline
spec:
  workspaces:
    - name: git-clone-workspace
    - name: git-credentials
    - name: docker-credentials
  params:
    - name: git-repo-url
      description: The private Git repository URL
      type: string
      default: git@github.com:hkb3711220/ProfileSite2.git
    - name: revision
      description: The private GitHub revision to use
      type: string
      default: main
    - name: image-reference
      description: HOST-NAME/PROJECT-ID/REPOSITORY/IMAGE
      type: string
  tasks:
    - name: git-clone
      taskRef: 
        name: git-clone
      params:
        - name: url
          value: $(params.git-repo-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: git-clone-workspace
        - name: ssh-directory
          workspace: git-credentials
    - name: build-image
      taskRef:
        name: kaniko
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: git-clone-workspace
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: $(params.image-reference)

    
