apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: git-clone-pipeline-trigger-eventlistener
spec:
  serviceAccountName: eventlistener-sa
  triggers:
    - name: git-clone-pipeline-trigger
      bindings:
        - ref: git-clone-pipeline-trigger-binding
      template:
        ref: git-clone-pipeline-trigger-template
      interceptors:
        - ref:
            name: "github"
          params:
          - name: "secretRef"
            value:
              secretName: github-secret
              secretKey: secretToken
          - name: "eventTypes"
            value: ["push"]

