apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-clone-pipeline
spec:
  workspaces:
    - name: git-clone-workspace
    - name: git-cred
  params:
    - name: url
      description: The private Git repository URL
      type: string
    - name: revision
      description: The private GitHub revision to use
      type: string
      default: main
  tasks:
    - name: git-clone
      taskRef: 
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: git-clone-workspace
        - name: ssh-directory
          workspace: git-cred
    - name: check-result
      runAfter:
        - git-clone
      taskRef:
        name: check-workspace
      workspaces:
        - name: source
          workspace: git-clone-workspace