apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-admin
secrets:
  - name: git-cred

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-admin-role
rules:
  - apiGroups: ["*"]
    resources: ["pod", "deployments", "services"]
    verbs: ["*"] #full-control

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-admin-role
subjects:
  - kind: ServiceAccount
    name: tekton-admin

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventlistener-sa

---
# EventListenerに必要なRole
# EventListener Podが、TriggerTemplateやTrigger Bindings、
# ConfigMapなどのKubernetesリソースを操作するからです。
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eventslistener-role
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggers
  - triggerbindings
  - triggertemplates
  - interceptors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  - taskruns
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eventlistener-cluster-role
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - clustertriggerbindings
  - clusterinterceptors
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eventlistener-role-binding
subjects:
  - kind: ServiceAccount
    name: eventlistener-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eventslistener-role

---
## 追加
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-clusterrole-binding
subjects:
  - kind: ServiceAccount
    name: eventlistener-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventlistener-cluster-role
