apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-workspace
spec:
  workspaces:
    - name: source
  steps:
    - name: build-sources
      image: ubuntu
      command:
        - /bin/bash
      args: ['-c', 'ls workspace/source']