apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-git-clone-result
spec:
  workspaces:
    - name: source
  steps:
    - name: check-result
      image: ubuntu
      command:
        - /bin/bash
      args: ['-c', 'ls workspace/source']